### ISSUE TITLE
リポジトリにbuildディレクトリの内容が含まれている

### ISSUE THREAD

**Issue by ochaochaocha3** [op3kitt/htmlddf#5]
buildディレクトリの内容をリポジトリに含めないようにし、代わりにGitHub上の[releases](https://github.com/op3kitt/htmlddf/releases)にbuildディレクトリの内容を圧縮したものを添付するようにすることを提案いたします。

**コミットには生成物の材料となるソースの変更のみを含めるべき**です。どどんとふ本体でもそうだったのですが、生成物をコミットに含めると、コミットが可読性のない生成物（ugilifyされているので実質的にバイナリファイルと同等）で肥大化します。これは、コミットの取得時間の増加や、変更点を見つけにくくなることにつながります。

圧縮ファイルの内容は、`gulp release` で生成されたbuildディレクトリの内容を1つのディレクトリに入れたものにすると、扱いやすくなると思われます。例えば、以下のようなものです。

```
htmlddf-0.1.4-dist.zip または htmlddf-0.1.4-dist.tar.gz

htmlddf-0.1.4-dist
├── css
├── img
├── index.html
├── js
└── sound
（2レベル以降省略）
```

このような内容ならば、以下の手順で簡単に生成物の圧縮ファイルを作ることができます。将来的には、gulpのtaskを作ることも可能でしょう。

1. `gulp clean && gulp release`
2. buildディレクトリを名前を変えてコピーする。
3. 圧縮する。

圧縮ファイル添付の手順は、以下のとおりです。

1. GitHubのリポジトリホームから飛べる[releases](https://github.com/op3kitt/htmlddf/releases)において、タグをもとにリリースを発行する。
2. リリースの編集画面の「Attach binaries by dropping them here or selecting them.」の欄を使って、圧縮ファイルを添付する。

**Comment by op3kitt** [comment]
ダーティーコミットというものでしょうかね。
実際ローカルビルドがリリース時に混入するなどの可能性もあったので.gitignoreも変更しました。

今までの配布用ビルドに対してはタグを発行しているので、取り入れるのは簡単そうです。
次回のリリースから採用させてもらおうかと思います。
